name: Docker Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      if: env.CR_PAT != '' || github.token != ''
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT || secrets.GITHUB_TOKEN }}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
        
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/wedding-outreach:latest
          ghcr.io/${{ github.repository_owner }}/wedding-outreach:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v5
      if: env.CR_PAT != '' || github.token != ''
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/wedding-outreach:latest
          ghcr.io/${{ github.repository_owner }}/wedding-outreach:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
      env:
        CR_PAT: ${{ secrets.CR_PAT }}